- hosts: all
  tasks:
   - name: Add epel repository
     yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

   - name: Add CentOS updates repository
     yum_repository:
      name: updates
      description: CentOS-$releasever - Updates
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
      enabled: 1
      gpgkey: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7

   - name: import rpm pgp key
     rpm_key:
      state: present
      key: "{{ item }}"
     with_items:
      - http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
      - https://muug.ca/mirror/fedora-epel//RPM-GPG-KEY-EPEL-7

   - name: upgrade all packages
     yum:
      name: "*"
      state: latest

   - name: Install Openvswitch 
     yum:
      name: openvswitch
      state: present

- hosts: masters etcd
  tasks:
   - name: Install prerequisites packages
     action: >
       {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
     with_items:
       - python-passlib
       - httpd-tools
       - java-1.8.0-openjdk-headless

   - name: Check control node to see if htpasswd is installed
     local_action: shell which htpasswd > /root/toto
     register: htpasswd_check
     failed_when: no
     changed_when: no

   - fail: msg="'htpasswd' is unavailable. Please install httpd-tools on the control node"
     when: htpasswd_check.rc  == 1

   - name: Check control node to see if keytool is installed
     local_action: command which keytool
     register: keytool_check
     failed_when: no
     changed_when: no

   - fail: msg="'keytool' is unavailable. Please install java-1.8.0-openjdk-headless on the control node"
     when: keytool_check.rc  == 1

